query getPriceBySkuId($skuId: Int, $skuReference: String, $productQuantity: Int) {
  getPriceBySkuId(skuId: $skuId, skuReference: $skuReference, productQuantity: $productQuantity) {
    itemId
    listPrice
    costPrice
    markup
    basePrice
  }
}
