query getMdHaveWishlist ($acronym: String, $fields: [String], $pageSize: Int) {
  documents(acronym: $acronym, fields: $fields, pageSize: $pageSize)
  @context(provider: "vtex.store-graphql") {
    id
    fields {
      key
      value
    }
  }
}